# Generated by Django 3.2.8 on 2021-10-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
