# Generated by Django 3.2.8 on 2021-10-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_genre_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movies/default.jpg', upload_to='movies/'),
        ),
    ]
